// Reads the live figures into src/stats.ts so a render never ships a stale number.
//
// The relayer is still running, so anything typed into the composition is wrong within the
// hour - the same reason the landing page counts from chain instead of hardcoding. Run this
// immediately before the final render.
const fs = require('fs');
const API = process.env.MERITR_API || 'https://meritr.38.49.216.120.sslip.io';

(async () => {
  const [att, res] = await Promise.all([
    fetch(`${API}/api/attestations`).then((r) => r.json()),
    fetch(`${API}/api/restructurings`).then((r) => r.json()),
  ]);
  const agent = '0xc06b60156473a15ed4505691403eef1f7650a2a5';
  const byAgent = res.events.filter((e) => e.triggeredBy.toLowerCase() === agent);
  const usd = (n) => (n >= 1e6 ? `$${(n / 1e6).toFixed(1)}M` : `$${Math.round(n).toLocaleString('en-US')}`);

  const stats = {
    facts: att.facts.toLocaleString('en-US'),
    borrowers: att.borrowers.toLocaleString('en-US'),
    valueProven: usd(att.valueProvenUsd),
    restructurings: res.count,
    agentRestructurings: byAgent.length,
    topRetiredUsd: byAgent.length ? usd(Math.max(...byAgent.map((e) => e.debtRetiredUsd))) : '$0',
    readAt: new Date().toISOString().slice(0, 10),
  };
  fs.writeFileSync(
    'src/stats.ts',
    '// Generated by fetch-stats.js from the live deployment. Do not edit by hand.\n' +
      `export const STATS = ${JSON.stringify(stats, null, 2)} as const;\n`,
  );
  console.log(`  ${stats.facts} facts · ${stats.borrowers} borrowers · ${stats.valueProven}`);
  console.log(`  ${stats.restructurings} restructurings, ${stats.agentRestructurings} by the agent`);
})();
