// Writes src/clips.ts from what is actually in public/clips.
//
// Remotion renders in a browser and cannot stat the filesystem, and OffthreadVideo throws at
// the compositor - before any onError handler - when a source 404s. So the composition asks a
// generated manifest instead, and renders a labelled placeholder for anything not yet recorded.
// That keeps the video renderable while the screen captures are still being made.
const fs = require('fs');
const dir = 'public/clips';
fs.mkdirSync(dir, { recursive: true });
const present = fs.readdirSync(dir).filter((f) => f.endsWith('.mp4')).map((f) => `clips/${f}`);

// Narration too. A missing mp3 aborts a render the same way a missing clip does, and the whole
// point of this manifest is that the video stays renderable while its assets are still being
// made - silent and placeheld, but watchable end to end.
const voDir = 'public/vo';
fs.mkdirSync(voDir, { recursive: true });
const vo = fs.readdirSync(voDir).filter((f) => f.endsWith('.mp3')).map((f) => `vo/${f}`);

fs.writeFileSync(
  'src/clips.ts',
  '// Generated by sync-clips.js. Do not edit by hand.\n' +
    `export const PRESENT_CLIPS: readonly string[] = ${JSON.stringify(present, null, 2)};\n` +
    `export const PRESENT_VO: readonly string[] = ${JSON.stringify(vo, null, 2)};\n`,
);
console.log(present.length ? `  clips: ${present.join(', ')}` : '  no clips yet - placeholders will render');
console.log(vo.length ? `  narration: ${vo.length} file(s)` : '  no narration yet - rendering silent');
